title: Welcome to My Blog
author: Marcus Munyiri
email: marcusmunyiri@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This my Awesome Website
  Describes all about me

# social links
twitter_username: marcusmunyiri # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
